# Generated by Django 4.0.1 on 2022-02-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_address_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
