# Generated by Django 4.0.1 on 2022-03-07 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name ')),
                ('salary', models.IntegerField(verbose_name='Salary ')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=100, verbose_name='Gender')),
                ('derpartment', models.CharField(max_length=100, verbose_name='Derpartment')),
                ('work_time', models.CharField(max_length=500, verbose_name='work time')),
                ('workdays', models.CharField(max_length=500, verbose_name='workdays')),
                ('picture', models.ImageField(upload_to='nures/')),
            ],
            options={
                'verbose_name': 'Nures ',
                'verbose_name_plural': 'Nurses',
            },
        ),
        migrations.CreateModel(
            name='OtherEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name ')),
                ('salary', models.IntegerField(verbose_name='Salary ')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=100, verbose_name='Gender')),
                ('type_of_job', models.CharField(max_length=300, verbose_name='Type Of Job ')),
                ('derpartment', models.CharField(max_length=100, verbose_name='Derpartment')),
                ('work_time', models.CharField(max_length=500, verbose_name='work time')),
                ('workdays', models.CharField(max_length=500, verbose_name='workdays')),
                ('picture', models.ImageField(upload_to='employee/')),
            ],
            options={
                'verbose_name': 'Other Employee',
                'verbose_name_plural': 'Other Employees',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=120, verbose_name='first name')),
                ('last_name', models.CharField(max_length=120, verbose_name='last name')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=100, verbose_name='Gender')),
                ('age', models.CharField(max_length=100, null=True, verbose_name='age')),
                ('speciality', models.CharField(max_length=120)),
                ('picture', models.ImageField(upload_to='doctors/')),
                ('address', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('experience', models.CharField(max_length=250, verbose_name='Experience in year')),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('On Leave', 'On Leave'), ('Not Available', 'Not Available')], max_length=20, verbose_name='Availability')),
                ('working_days', models.CharField(max_length=250, verbose_name='Working Days')),
                ('expertize', models.ManyToManyField(blank=True, null=True, related_name='doctors', to='staff.Expertize')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
    ]
