# Generated by Django 4.0.1 on 2022-03-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='working_days',
            field=models.CharField(max_length=250, verbose_name='workdays'),
        ),
    ]
