# Generated by Django 4.0.1 on 2022-03-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_doctor_working_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='expertize',
            field=models.ManyToManyField(related_name='doctors', to='staff.Expertize'),
        ),
    ]
