# Generated by Django 4.0.1 on 2022-01-27 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=120)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='gallery/')),
            ],
            options={
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='Heart_Care_Basics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('book', models.FileField(blank=True, null=True, upload_to='pdf/', verbose_name='pdf')),
            ],
            options={
                'verbose_name_plural': 'Heart Care Basicses',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=150)),
                ('slogan', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='sliders/')),
            ],
            options={
                'verbose_name_plural': 'Slider',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='services/')),
                ('cover', models.ImageField(upload_to='services/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('items', models.ManyToManyField(to='hospital.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='last_name')),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='PatientProfilePic/', verbose_name='profile picture')),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'patients profiles',
            },
        ),
        migrations.CreateModel(
            name='Inpatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('age', models.CharField(max_length=100, verbose_name='age')),
                ('weight', models.CharField(max_length=100, verbose_name='Weight')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=100, verbose_name='Gender')),
                ('number', models.CharField(max_length=100, verbose_name='Number')),
                ('Ward', models.CharField(max_length=100, verbose_name='Ward')),
                ('Bed', models.CharField(max_length=100, verbose_name='Bed')),
                ('diagnoses', models.CharField(max_length=255, verbose_name='Diagnoses')),
                ('operation_type', models.CharField(max_length=255, verbose_name='Operation Type')),
                ('entry_date_time', models.DateTimeField(auto_now_add=True, verbose_name='entry date time')),
                ('operation_date_time', models.DateTimeField(verbose_name='operation date time')),
                ('leaving_date_time', models.DateTimeField(verbose_name='leaving date time')),
                ('medications', models.TextField(verbose_name='Medications')),
                ('operative_finding', models.TextField(max_length=255, verbose_name='operative finding')),
                ('operative_procedure', models.TextField(max_length=255, verbose_name='operative procedure')),
                ('operative_note', models.TextField(max_length=255, verbose_name='operative note')),
                ('specimen_to_laboratory', models.BooleanField(verbose_name='specimen to laboratory')),
                ('consultant_surgeon', models.CharField(max_length=255, verbose_name='consultant surgeon')),
                ('co_surgeon', models.CharField(max_length=255, verbose_name='co_surgeon')),
                ('surgeon', models.CharField(max_length=255, verbose_name='surgeon')),
                ('anesthetist', models.CharField(max_length=255, verbose_name='anesthetist')),
                ('nurse', models.CharField(max_length=255, verbose_name='nurse')),
                ('sponge_nurse', models.CharField(max_length=255, verbose_name='sponge_nurse')),
                ('doctor_name', models.CharField(max_length=255, verbose_name='doctor_name')),
                ('flag', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inpatient',
                'verbose_name_plural': 'Inpatients',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('speciality', models.CharField(max_length=120)),
                ('picture', models.ImageField(upload_to='doctors/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('details', models.TextField()),
                ('experience', models.TextField()),
                ('twitter', models.CharField(blank=True, max_length=120, null=True)),
                ('facebook', models.CharField(blank=True, max_length=120, null=True)),
                ('instagram', models.CharField(blank=True, max_length=120, null=True)),
                ('expertize', models.ManyToManyField(related_name='doctors', to='hospital.Expertize')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('sending_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sending date')),
                ('visit_date', models.DateTimeField(blank=True, null=True, verbose_name='Visit date')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('completed', 'completed')], max_length=100)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='hospital.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appoinments', to='hospital.patient_profile')),
            ],
        ),
    ]
