# Generated by Django 4.0.1 on 2022-02-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inpatient',
            name='doctor',
        ),
    ]
