# Generated by Django 4.0.1 on 2022-02-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='details',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='twitter',
        ),
        migrations.AddField(
            model_name='doctor',
            name='availability',
            field=models.CharField(choices=[('Available', 'Available'), ('On Leave', 'On Leave'), ('Not Available', 'On Leave')], default=1, max_length=20, verbose_name='Availability'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_days',
            field=models.CharField(default=1, max_length=250, verbose_name='Working Days'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.CharField(max_length=250, verbose_name='Experience in year'),
        ),
    ]
