# Generated by Django 4.0.1 on 2022-03-08 19:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activae')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MEDICINE_NAME', models.CharField(max_length=500, verbose_name='Medicine Name')),
                ('SELLING_PRICE', models.IntegerField(verbose_name='Selling Price')),
                ('EXPIRE_DATE', models.DateField(verbose_name='Expire Date')),
                ('MANUFACTURE_NAME', models.CharField(max_length=500, verbose_name='Manufacture Name')),
                ('UNITARY_PRICE', models.IntegerField(verbose_name='Unitary Price')),
                ('QUANTITY', models.IntegerField(verbose_name='Quantity')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
            },
        ),
    ]
