# Generated by Django 4.0.1 on 2022-01-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='expertize',
            field=models.ManyToManyField(blank=True, null=True, related_name='doctors', to='hospital.Expertize'),
        ),
    ]
