# Generated by Django 4.0.1 on 2022-02-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_doctor_expertize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('requested', 'requested'), ('completed', 'completed')], max_length=100),
        ),
    ]
