# Generated by Django 4.0.1 on 2022-02-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inpatient',
            old_name='user',
            new_name='added_by',
        ),
        migrations.RemoveField(
            model_name='inpatient',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='patient_profile',
            name='status',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(max_length=120, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(max_length=120, verbose_name='last name'),
        ),
    ]
