# Generated by Django 4.0.1 on 2022-02-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_rename_mobile_doctor_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppointmentFromReceptiontst',
            new_name='InpatientAppointments',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default=1, max_length=100, verbose_name='Gender'),
            preserve_default=False,
        ),
    ]
