# Generated by Django 4.0.1 on 2022-02-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_rename_user_inpatient_added_by_remove_inpatient_flag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_profile',
            old_name='mobile',
            new_name='phone_number',
        ),
    ]
