# Generated by Django 4.0.1 on 2022-02-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_rename_mobile_patient_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='age',
            field=models.CharField(max_length=100, null=True, verbose_name='age'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=100, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='patient_profile',
            name='age',
            field=models.CharField(max_length=100, null=True, verbose_name='age'),
        ),
        migrations.AddField(
            model_name='patient_profile',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=100, null=True, verbose_name='Gender'),
        ),
    ]
