# Generated by Django 4.0.1 on 2022-03-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_contact_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='created_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='created date'),
        ),
    ]
