# Generated by Django 4.0.1 on 2022-03-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_prescription_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outpatients',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='PatientProfilePic/', verbose_name='profile picture'),
        ),
    ]
