# Generated by Django 4.0.1 on 2022-02-03 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_prescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='Prescription',
            new_name='prescription',
        ),
    ]
