# Generated by Django 4.0.1 on 2022-03-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_outpatients_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outpatients',
            name='profile_pic',
            field=models.ImageField(blank=True, default='PatientProfilePic/default.jpg', null=True, upload_to='PatientProfilePic/', verbose_name='profile picture'),
        ),
    ]
